/**
  ******************************************************************************
  * @file    MotorDriver_port.c
  * @author  
  * @version V1.0.0
  * @date    
  * @brief   This file provides set of portable functions to manage low level
	*					 operations of the Motor Bridge.
  *          
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include <MeSN_MotorDriver_port.h>		//check matching between prototype and implementation

/* External Variables --------------------------------------------------------*/

/* Private variables ---------------------------------------------------------*/
static TIM_HandleTypeDef handle_PWMTim;		//Peripheral handle for Timer generating PWM

/* Private prototypes ---------------------------------------------------------*/
static void HAL_TIM_MspPostInit(TIM_HandleTypeDef *htim);

/* Public Functions ----------------------------------------------------------*/
/**
	* @brief  Configures GPIO pins dedicated to motor direction:
	*         2 pins are required, in pushpull output mode.
  * @param  None
  * @retval None
  */
void MotorDriver_Port_GPIO_Init(void){
	
	//Peripheral initialization functions are generated by CubeMX software and
	//are note required anymore.
	//Review MX_GPIO_Init() function if needed

	GPIO_InitTypeDef GPIO_InitStruct;

	MOTOR_DIR_PORT_CLK_ENABLE();

	/*Configure GPIO pins : PB13 PB14 */
	GPIO_InitStruct.Pin = MOTOR_IN1_PIN|MOTOR_IN2_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(MOTOR_DIR_PORT, &GPIO_InitStruct);
	
	//Pull the two dirPin low (STOP)
	MotorDriver_Port_SetPin_IN1(GPIO_DIRPIN_LOW);
	MotorDriver_Port_SetPin_IN2(GPIO_DIRPIN_LOW);
	
}

/**
	* @brief  Configures Timer dedicated to PWM generation:
	*					1 PWM output pin are required,
	*					maximum PWM frequency is 100kHz.
  * @param  None
  * @retval None
  */
void MotorDriver_Port_PWM_Init(void){
	
	//Peripheral initialization functions are generated by CubeMX software and
	//are note required anymore.
	//Review MX_TIM10_Init() function in main.c if needed
	
	TIM_ClockConfigTypeDef sClockSourceConfig;
	TIM_OC_InitTypeDef sConfigOC;

	handle_PWMTim.Instance = MOTOR_PWM_TIM_INSTANCE;
	handle_PWMTim.Init.Prescaler = 0;
	handle_PWMTim.Init.CounterMode = TIM_COUNTERMODE_UP;
	handle_PWMTim.Init.Period = 1600;
	handle_PWMTim.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
	if (HAL_TIM_Base_Init(&handle_PWMTim) != HAL_OK)
	{
	_Error_Handler(__FILE__, __LINE__);
	}

	MOTOR_PWM_TIM_CLK_ENABLE();

	sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
	if (HAL_TIM_ConfigClockSource(&handle_PWMTim, &sClockSourceConfig) != HAL_OK)
	{
	_Error_Handler(__FILE__, __LINE__);
	}

	if (HAL_TIM_PWM_Init(&handle_PWMTim) != HAL_OK)
	{
	_Error_Handler(__FILE__, __LINE__);
	}

	sConfigOC.OCMode = TIM_OCMODE_PWM1;
	sConfigOC.Pulse = 0;
	sConfigOC.OCPolarity = TIM_OCPOLARITY_HIGH;
	sConfigOC.OCFastMode = TIM_OCFAST_DISABLE;
	if (HAL_TIM_PWM_ConfigChannel(&handle_PWMTim, &sConfigOC, MOTOR_PWM_TIM_CHANNEL) != HAL_OK)
	{
	_Error_Handler(__FILE__, __LINE__);
	}

	HAL_TIM_MspPostInit(&handle_PWMTim);

	//Start PWM generation
	HAL_TIM_PWM_Start(&handle_PWMTim, MOTOR_PWM_TIM_CHANNEL);
	
}

/**
	* @brief  Set direction pin value, IN1,
	*         according to parameter value
	* @param  pinState : GPIO_DIRPIN_LOW or GPIO_DIRPIN_HIGH
  * @retval None
  */
void MotorDriver_Port_SetPin_IN1(GPIO_DirPinState pinState){
	
	if (pinState == GPIO_DIRPIN_LOW){
		HAL_GPIO_WritePin(MOTOR_DIR_PORT, MOTOR_IN1_PIN, GPIO_PIN_RESET);
	}else{
		HAL_GPIO_WritePin(MOTOR_DIR_PORT, MOTOR_IN1_PIN, GPIO_PIN_SET);
	}
	
}

/**
	* @brief  Set direction pin value, IN2,
	*         according to parameter value
	* @param  pinState : GPIO_DIRPIN_LOW or GPIO_DIRPIN_HIGH
  * @retval None
  */
void MotorDriver_Port_SetPin_IN2(GPIO_DirPinState pinState){
	
	if (pinState == GPIO_DIRPIN_LOW){
		HAL_GPIO_WritePin(MOTOR_DIR_PORT, MOTOR_IN2_PIN, GPIO_PIN_RESET);
	}else{
		HAL_GPIO_WritePin(MOTOR_DIR_PORT, MOTOR_IN2_PIN, GPIO_PIN_SET);
	}
	
}

/**
	* @brief  Set PWM duty cycle on dedicated motor pin
	* @param  dutyCycle : desired duty cycle.
	*         Must be a number between 0 and PWM_DUTYCYCLE_FULL_SCALE
  * @retval None
  */
void MotorDriver_Port_SetPWM(uint32_t dutyCycle){
	
	if(dutyCycle <= PWM_DUTYCYCLE_FULL_SCALE){
		handle_PWMTim.Instance->CCR1 = dutyCycle;
	}
	
}

/* Private functions ----------------------------------------------------------*/
static void HAL_TIM_MspPostInit(TIM_HandleTypeDef* timHandle)
{

  GPIO_InitTypeDef GPIO_InitStruct;
  if(timHandle->Instance==TIM10)
  {
    /* TIM10 GPIO Configuration  */

	MOTOR_PWM_PORT_CLK_ENABLE();

    GPIO_InitStruct.Pin = MOTOR_PWM_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF3_TIM10;
    HAL_GPIO_Init(MOTOR_PWM_PORT, &GPIO_InitStruct);
  }

}
/**********END OF FILE****/
